<?php
/**
 * Example PHP Enhancement Script for Migrations
 * 
 * This script demonstrates how to generate SQL with serialized data.
 * It will be executed before the matching SQL file and can generate
 * additional SQL statements with properly serialized PHP data.
 * 
 * Usage: This script is automatically called by migrations.sh
 * Arguments: $argv[1] = WordPress path
 */

if ($argc < 2) {
    echo "-- Error: WordPress path not provided\n";
    exit(1);
}

$wp_path = $argv[1];

// Example: Generate serialized data for WordPress options
$example_options = [
    'my_custom_setting' => [
        'enabled' => true,
        'features' => ['feature1', 'feature2', 'feature3'],
        'config' => [
            'timeout' => 30,
            'retries' => 3,
            'debug' => false
        ]
    ],
    'my_plugin_data' => [
        'version' => '1.0.0',
        'installed_at' => date('Y-m-d H:i:s'),
        'settings' => [
            'theme' => 'dark',
            'notifications' => true,
            'auto_update' => false
        ]
    ]
];

echo "-- Generated by PHP enhancement script\n";
echo "-- Adding serialized options data\n\n";

foreach ($example_options as $option_name => $option_value) {
    $serialized_value = serialize($option_value);
    $escaped_value = addslashes($serialized_value);
    
    echo "INSERT INTO wp_options (option_name, option_value, autoload) VALUES ";
    echo "('$option_name', '$escaped_value', 'yes') ";
    echo "ON DUPLICATE KEY UPDATE option_value = VALUES(option_value);\n\n";
}

echo "-- End of PHP-generated SQL\n";
